@startuml
!pragma layout smetana
== Запрос на Расчет ==
activate Пользователь
activate Сервис_сбора_метрик
activate База_данных_или_Файл

Пользователь -> Сервис_сбора_метрик: Запрос метрики
alt Если ошибка валидации
    Сервис_сбора_метрик -> Пользователь: Ошибка
else Запрос валидирован
    Сервис_сбора_метрик  -> База_данных_или_Файл: Запрос метрики
    База_данных_или_Файл  -> Сервис_сбора_метрик: Метрика
    Сервис_сбора_метрик -> Пользователь: Метрика
end
@enduml