@startuml
!pragma layout smetana
== Запрос на Расчет ==
activate Клиент
activate Сервис_сбора_метрик
activate База_данных_или_Файл
Клиент -> Сервис_сбора_метрик: Отправка метрики
alt Если ошибка валидации
    Сервис_сбора_метрик -> Клиент: Ошибка
else Метрика валидирована
    Сервис_сбора_метрик -> База_данных_или_Файл: Записать метрику
    alt Если ошибка записи
        База_данных_или_Файл -> Сервис_сбора_метрик: Ошибка
        Сервис_сбора_метрик -> Клиент: Ошибка
    else Ошибки нет
        База_данных_или_Файл -> Сервис_сбора_метрик: Ок
        Сервис_сбора_метрик -> Клиент: Ок
    end
end
@enduml