version: "3.3"
services:
  db:
    image: postgres:latest
    restart: always
    volumes:
      - /tmp/postgres_data/:/var/lib/postgresql/data/
    ports:
      - "127.0.0.1:5432:5432"
    command: >
      postgres
      -c shared_preload_libraries='pg_stat_statements'
    env_file:
      - .env



