version: "3.3"
services:
  db:
    image: postgres:16.1-alpine
    restart: always
    volumes:
      - /tmp/postgres_data/:/var/lib/postgresql/data/
    ports:
      - "127.0.0.1:5432:5432"
    env_file:
      - .env