// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  v3

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( MetricHandlers ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* MetricHandlers ) UnmarshalJSON([]byte) error { return nil }
func ( MetricHandlers ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* MetricHandlers ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_MetricHandlers *MetricHandlers
